spring:
  application:
    name: recommendation-service

server:
  port: 7003

logging:
  level:
    root: INFO
    com.microservices.core: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080