spring:
  application:
    name: recommendation-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db
  cloud:
    stream:
      defaultBinder: kafka
      default.contentType: application/json
      bindings:
        consumeEvent-in-0:
          destination: recommendations
          group: recommendationGroup
          maxAttempts: 3
          backOffInitialInterval: 500
          backOffMaxInterval: 1000
          backOffMultiplier: 2.0
      kafka:
        enableDlq: true
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092
server:
  port: 7003

logging:
  level:
    root: INFO
    com.microservices.core: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          defaultBrokerPort: 9092
          replication-factor: 1

server:
  port: 8080

app:
  eureka-server: eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5