spring:
  application:
    name: recommendation-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db
server:
  port: 7003

logging:
  level:
    root: INFO
    com.microservices.core: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb

server:
  port: 8080